### ISSUE TITLE
Problems running on OSX

### ISSUE THREAD

**Issue by amjjbonvin** [h2020-westlife-eu/wp4-accounting#1]
west-life/wp4-accounting> python accounting.py -i https://accounting.egi.eu/egi/htc/njobs/SITE/VO/2017/01/2017/06/custom-enmr.eu/onlyinfrajobs/CSV 2
Traceback (most recent call last):
  File "accounting.py", line 4, in <module>
    import requests
ImportError: No module named requests

Using python version 2.7.10
Where is the requests module coming from?

**Comment by marcoverl** [comment]
you must install the requests module, i guess that doing $ pip install requests from your Mac should fix the problem

**Comment by ljocha** [comment]
I've seen the same, and the suggested pip command did the job. Just beware of mixing python 2.7 and 3.x, it's a bit tricky. Check which version is your pip first.

**Comment by amjjbonvin** [comment]
Thanks - then software dependencies should be indicated on GitHub.

But indeed installing it makes it work!

**Comment by marcoverl** [comment]
ok, requirements.txt file added on GitHub
